#%RAML 1.0 ResourceType
uses:
  error_warning: ../libraries/error_warning_types.raml

get?:
  headers:
    
  responses:
    200:
      description: |
        
      headers:
        
    204:
      description: |
        
      headers:        

    400:
      description: Incorrect parameters
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_400.json
    401:
      description: Not Authorized
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_401.json

    403:
      description: Access Forbidden
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_403.json

    404:
      description: Not Found
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_404.json
    
post?:
  headers:
    
  responses:
    200:
      description: |
        
      headers:
        
    204:
      description: |
        
      headers:        

    400:
      description: Incorrect parameters
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_400.json
    401:
      description: Not Authorized
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_401.json

    403:
      description: Access Forbidden
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_403.json

    404:
      description: Not Found
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_404.json

put?:
  headers:
   
  responses:
    200:
      description: |
        
      headers:
        
    204:
      description: |
        
      headers:        

    400:
      description: Incorrect parameters
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_400.json
    401:
      description: Not Authorized
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_401.json

    403:
      description: Access Forbidden
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_403.json

    404:
      description: Not Found
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_404.json

patch?:
  headers:
    
  responses:
    200:
      description: |
        
      headers:
        
    204:
      description: |
        
      headers:        

    400:
      description: Incorrect parameters
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_400.json
    401:
      description: Not Authorized
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_401.json

    403:
      description: Access Forbidden
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_403.json

    404:
      description: Not Found
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_404.json

delete?:
  headers:
    
  responses:
    200:
      description: |
        
      headers:
        
    204:
      description: |
        
      headers:        

    400:
      description: Incorrect parameters
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_400.json
    401:
      description: Not Authorized
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_401.json

    403:
      description: Access Forbidden
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_403.json

    404:
      description: Not Found
      body:
        application/json:
          properties:
            messages:
              type: error_warning.message[]
              example: !include ../examples/errors/error_404.json
