#%RAML 1.0
title: API Dashboard Mapserv 
version: v1

baseUri:
  value: http://{environment}-dashboard-mapserv.herokuapp.com/{version}
  
baseUriParameters:
  environment:
    type: string
    enum: [ "stg", "dev", "test", "prod" ]
    
protocols: [ HTTP, HTTPS ]
mediaType: [ application/json ]
documentation:
  - !include docs/intro.doc.raml
  
uses:
  resourceTypesLib: modules/resource-types.lib.raml
  traitsLib: modules/traits.lib.raml
  
/maps:
  type: resourceTypesLib.collection  
  get:
    description: List of all maps
    is: [traitsLib.searchable, traitsLib.pageable]
    responses:
      200:
        body:
          application/json:
            type: resourceTypesLib.typesLib.GetMapsResponse
            example: 
              links:
                - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps?pageIndex=30&pageSize=10
                  rel: next
                - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps?pageIndex=10&pageSize=10
                  rel: prev
                - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps?pageIndex=20&pageSize=10
                  rel: self
              collection:
                size: 2
                maps:
                  - name: bacias
                    links:
                      - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps/bacias
                        rel: self
                  - name: Cidades            
                    links:
                      - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps/Cidades
                        rel: self    
  post:
    description: Add an Map to my Maps List.  
    body:
      type: resourceTypesLib.typesLib.PostMapsRequest  
  /{map}:
    type: resourceTypesLib.member
    get:
      description: Get Map from Maps list
      responses:
        200:
          body:
            application/json:
              type: resourceTypesLib.typesLib.GetMapResponse
              example: 
                links:
                  - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps/Cidades
                    rel: next
                  - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps/Estados
                    rel: prev
                  - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps/bacias
                    rel: self
                name: bacias
    put:
      description: Update Map
      body:
        type: resourceTypesLib.typesLib.PutMapRequest  
    delete:
      description: Remove from Maps list
      
/mapserv:
  #type: [base]
  get:
    responses:
      200:
        description: Mapserv.
        body:
          application/json:
            type: resourceTypesLib.typesLib.Mapserv
            example: !include ./examples/200_mapserv.raml 