#%RAML 1.0 Library

uses:
  annotations: annotations.lib.raml
  
types:
  ResourceLink:
    type: object
    properties:
      href: string
      rel:
        enum: [self, next, prev]
      method?:
        default: get
        
  Mapserv:
    type: object
    description: "Mapserv data"
    properties:
      data:
        description: "Data from mapserv"
        type: string
        
  Map:
    type: object
    properties:
      name: string
      links: ResourceLink[]  

  GetMapsResponse:
    type: object
    properties:
      links: ResourceLink[]
      collection:
        properties:
          size: integer
          maps: Map[]      
                
  PostMapsRequest:
    type: object
    properties:
      name: string
    example:
      name: bacias
                    
  GetMapResponse:
    type: Map    
    example:
      links:
        - href: http://prod-dashboard-mapserv.herokuapp.com/rest/v1/maps/bacias
          rel: self      
      name: bacias  
      
  PutMapRequest:
    type: object
    properties:
      name: string
    example:
      name: bacias   
      
  PatchMapRequest:
    type: object
    properties:
      name: string
    example:
      name: bacias   